---
title: "Schedule"
description: |
 Schedule and course materials for Statistical Computing (JHSPH Biostatistics 140.776 Fall 2022).
tbl-colwidths: [15,10, 55, 25]
---

## Schedule and course materials

For Qmd files (markdown document with [Quarto](https://quarto.org/docs/authoring/markdown-basics.html) cross-language executable code), go to the [course GitHub repository](https://github.com/stephaniehicks/jhustatcomputing2022) and navigate the directories, or best of all to clone the repo and navigate within RStudio.

::: column-page
| Week         | Dates   | Topics                                                                                                                                                                                                                                                                                                 | Projects                                                                                                                                                                                                            |     |
|---------------|---------------|---------------|---------------|---------------|
| **Module 1** |         | **Statistical and computational tools for scientific and reproducible research**                                                                                                                                                                                                                       |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| Week 1       | Aug 30  | `r emojifont::emoji('wave')` Course introduction \[[html](posts/welcome/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/welcome/index.qmd)\]                                                                                                               | `r emojifont::emoji('palm_tree')` Project 0 \[[html](projects/2022-08-30-project-0/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/projects/2022-08-30-project-0/index.qmd)\] |     |
|              |         | `r emojifont::emoji('woman_technologist')` Introduction to R and RStudio \[[html](posts/2022-08-30-introduction-to-r-and-rstudio/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-08-30-introduction-to-r-and-rstudio/index.qmd)\]                     |                                                                                                                                                                                                                     |     |
|              |         | `r emojifont::emoji('octopus')` Introduction to git/GitHub \[[html](posts/2022-08-30-introduction-to-gitgithub/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-08-30-introduction-to-gitgithub/index.qmd)\]                                           |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Sept 1  | `r emojifont::emoji('microscope')` Reproducible Research \[[html](posts/2022-09-01-reproducible-research/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-01-reproducible-research/index.qmd)\]                                                     |                                                                                                                                                                                                                     |     |
|              |         | `r emojifont::emoji('eyeglasses')` Literate programming \[[html](posts/2022-09-01-literate-programming/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-01-literate-programming/index.qmd)\]                                                        |                                                                                                                                                                                                                     |     |
|              |         | `r emojifont::emoji('cool')` Reference management \[[html](posts/2022-09-01-reference-management/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-01-reference-management/index.qmd)\]                                                              |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| **Module 2** |         | **Data analysis in R**                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| Week 2       | Sept 6  | `r emojifont::emoji('eyes')` Reading and writing data \[[html](posts/2022-09-06-reading-and-writing-data/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-06-reading-and-writing-data/index.qmd)\]                                                  | `r emojifont::emoji('palm_tree')` Project 1 \[[html](projects/2022-09-06-project-1/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/projects/2022-09-06-project-1/index.qmd)\] |     |
|              |         | `r emojifont::emoji('scissors')` Managing data frames with Tidyverse \[[html](posts/2022-09-06-managing-data-frames-with-tidyverse/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-06-managing-data-frames-with-tidyverse/index.qmd)\]             |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Sept 8  | `r emojifont::emoji('heart_eyes_cat')` Tidy data and the Tidyverse \[[html](posts/2022-09-08-tidy-data-and-the-tidyverse/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-08-tidy-data-and-the-tidyverse/index.qmd)\]                               | `r emojifont::emoji('fallen_leaf')` Project 0 due                                                                                                                                                                   |     |
|              |         | `r emojifont::emoji('handshake')` Joining data in R: Basics \[[html](posts/2022-09-08-joining-data-in-r/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-08-joining-data-in-r/index.qmd)\]                                                          |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| **Module 3** |         | **Data visualizations R**                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| Week 3       | Sept 13 | `r emojifont::emoji('bar_chart')` Plotting systems in R \[[html](posts/2022-09-13-plotting-systems/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-13-plotting-systems/index.qmd)\]                                                                |                                                                                                                                                                                                                     |     |
|              |         | `r emojifont::emoji('bar_chart')` The ggplot2 plotting system: qplot() \[[html](posts/2022-09-13-ggplot2-plotting-system-part-1/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-13-ggplot2-plotting-system-part-1/index.qmd)\]                     |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Sept 15 | `r emojifont::emoji('bar_chart')` The ggplot2 plotting system: ggplot() \[[html](posts/2022-09-15-ggplot2-plotting-system-part-2/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-15-ggplot2-plotting-system-part-2/index.qmd)\]                    | `r emojifont::emoji('palm_tree')` Project 2 \[[html](projects/2022-09-15-project-2/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/projects/2022-09-15-project-2/index.qmd)\] |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Sept 16 |                                                                                                                                                                                                                                                                                                        | `r emojifont::emoji('fallen_leaf')` Project 1 due                                                                                                                                                                   |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| **Module 4** |         | **Nuts and bolts of R**                                                                                                                                                                                                                                                                                |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| Week 4       | Sept 20 | `r emojifont::emoji('nut_and_bolt')` R Nuts and Bolts \[[html](posts/2022-09-20-r-nuts-and-bolts/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-20-r-nuts-and-bolts/index.qmd)\]                                                                  |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Sept 22 | `r emojifont::emoji('nut_and_bolt')` Control structures in R \[[html](posts/2022-09-22-control-structures/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-22-control-structures/index.qmd)\]                                                       |                                                                                                                                                                                                                     |     |
|              |         | `r emojifont::emoji('nut_and_bolt')` Functions in R \[[html](posts/2022-09-22-functions/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-22-functions/index.qmd)\]                                                                                  |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| Week 5       | Sept 27 | `r emojifont::emoji('nut_and_bolt')` Loop functions \[[html](posts/2022-09-27-loop-functions/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-27-loop-functions/index.qmd)\]                                                                        |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Sept 29 | `r emojifont::emoji('bug')` Debugging code in R \[[html](posts/2022-09-29-debugging-r-code/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-29-debugging-r-code/index.qmd)\]                                                                        |                                                                                                                                                                                                                     |     |
|              |         | `r emojifont::emoji('bug')` Error handling code in R \[[html](posts/2022-09-29-error-handling-and-generation/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-09-29-error-handling-and-generation/index.qmd)\]                                         |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Sept 30 |                                                                                                                                                                                                                                                                                                        | `r emojifont::emoji('fallen_leaf')` Project 2 due                                                                                                                                                                   |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| **Module 5** |         | **Special data types in R**                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| Week 6       | Oct 4   | `r emojifont::emoji('calendar')` Working with dates and times \[[html](posts/2022-10-04-working-with-dates-and-times/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-10-04-working-with-dates-and-times/index.qmd)\]                                  | `r emojifont::emoji('palm_tree')` Project 3 \[[html](projects/2022-10-04-project-3/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/projects/2022-10-04-project-3/index.qmd)\] |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Oct 6   | `r emojifont::emoji('sparkles')` Regular expressions \[[html](posts/2022-10-06-regular-expressions/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-10-06-regular-expressions/index.qmd)\]                                                             |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| Week 7       | Oct 11  | `r emojifont::emoji('cat')` Working with factors \[[html](posts/2022-10-11-working-with-factors/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-10-11-working-with-factors/index.qmd)\]                                                               |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Oct 13  | `r emojifont::emoji('calendar')` Working with text data and sentiment analysis \[[html](posts/2022-10-13-working-with-text-sentiment-analysis/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-10-13-working-with-text-sentiment-analysis/index.qmd)\] |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| **Module 6** |         | **Best practices for working with data and other languages**                                                                                                                                                                                                                                           |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
| Week 8       | Oct 18  | `r emojifont::emoji('cloud')` Best practices for storing data                                                                                                                                                                                                                                          |                                                                                                                                                                                                                     |     |
|              |         | `r emojifont::emoji('cloud')` Best practices for ethical data analysis                                                                                                                                                                                                                                 |                                                                                                                                                                                                                     |     |
|              |         | `r emojifont::emoji('cloud')` Best practices for project-oriented workflows in R                                                                                                                                                                                                                       |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Oct 20  | `r emojifont::emoji('snake')` Leveraging Python within R \[[html](posts/2022-10-20-python-for-r-users/index.qmd)\] \[[Qmd](https://github.com/stephaniehicks/jhustatcomputing2022/blob/main/posts/2022-10-20-python-for-r-users/index.qmd)\]                                                                                                                                                                                                                                              |                                                                                                                                                                                                                     |     |
|              |         |                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                     |     |
|              | Oct 21  |                                                                                                                                                                                                                                                                                                        | `r emojifont::emoji('fallen_leaf')` Project 3 due                                                                                                                                                                   |     |
:::
